version: '3.8'

networks:
  server-connection:
    driver: bridge
  db-connection:
    driver: bridge

services:
  db:
    image: mariadb:latest
    container_name: db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: pic2post
      MYSQL_USER: hojae
      MYSQL_PASSWORD: lemon.odi
      MYSQL_ROOT_PASSWORD: password
    networks:
     - db-connection
    volumes:
      - "./mariadb/conf.d:/etc/mysql/conf.d"
      - "./mariadb/data:/var/lib/mysql"
  nginx:
    image: nginx:latest
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./server/frontend/static:/data/static
    networks:
      - server-connection
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - pic2post
  pic2post:
    container_name: pic2post
    restart: always
    build:
      context: .
      dockerfile: ./server/Dockerfile
    command: >
      bash -c "
      python manage.py migrate
      && gunicorn --bind 0.0.0.0:8000 server.wsgi"
    expose:
      - "8000"
    networks:
      - db-connection
      - server-connection
    depends_on:
      - db
    volumes:
      - ./server:/server
    env_file:
      - ./server/.env